language: node_js
node_js:
  - '0.10'
before_script:
  - npm install
  - npm install -g mocha
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-helloworld' ]; then cd .. && eval "mv $currentfolder generator-helloworld" && cd generator-helloworld; fi
  - mocha --reporter spec ./test/test-app.js